version: "3"
services:
    judgehost:
        image: "domjudge/judgehost:latest"
        environment:
            DOMSERVER_BASEURL: YOUR_DOMSERVER_BASEURL
            JUDGEDAEMON_USERNAME: judgehost
            JUDGEDAEMON_PASSWORD: YOUR_JUDGEHOST_PASSWORD
            DAEMON_ID: 0
            CONTAINER_TIMEZONE: Asia/Shanghai
        privileged: true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro

