version: "3"
services:
    domserver:
        image: "registry.cn-beijing.aliyuncs.com/toxtricity/domserver:bcpc-special-register"
        restart: unless-stopped
        ports:
            - "YOUR_PORT:80"
        environment:
            MYSQL_PASSWORD: YOUR_MYSQL_PASSWORD
            MYSQL_ROOT_PASSWORD: YOUR_MYSQL_ROOT_PASSWORD
            MYSQL_HOST: YOUR_MYSQL_CONTAINER_NAME
            CONTAINER_TIMEZONE: YOUR/TIME_ZONE
            BEIAN_CONTENT: 京ICP备20018844号-2
    YOUR_MYSQL_CONTAINER_NAME:
        image: "mysql:5.7.36"
        restart: unless-stopped
        # If you have a huge **single** test case, setup max_allowed_packet and innodb-log-file-size
        # innodb-log-file-size is at least 10 times bigger than the largest test case
        command: --max-connections=1000 --max_allowed_packet=512M
        environment:
            MYSQL_USER: domjudge
            MYSQL_DATABASE: domjudge
            MYSQL_PASSWORD: YOUR_MYSQL_PASSWORD
            MYSQL_ROOT_PASSWORD: YOUR_MYSQL_ROOT_PASSWORD
        volumes:
            - /YOUR/HOST/DATA/PATH:/var/lib/mysql
