version: "3"
services:
    domserver:
        image: "toxtricity/domserver:v3"
        ports:
            - "YOUR_PORT:80"
        environment:
            MYSQL_PASSWORD: YOUR_MYSQL_PASSWORD
            MYSQL_ROOT_PASSWORD: YOUR_MYSQL_ROOT_PASSWORD
            MYSQL_HOST: YOUR_MYSQL_CONTAINER_NAME
            CONTAINER_TIMEZONE: YOUR/TIME_ZONE
    YOUR_MYSQL_CONTAINER_NAME:
        image: "mysql:5.7.36"
        # If you have a huge **single** test case, setup this command
        # command: --max_allowed_packet=67108864
        environment:
            MYSQL_USER: domjudge
            MYSQL_DATABASE: domjudge
            MYSQL_PASSWORD: YOUR_MYSQL_PASSWORD
            MYSQL_ROOT_PASSWORD: YOUR_MYSQL_ROOT_PASSWORD
        volumes:
            - /YOUR/HOST/DATA/PATH:/var/lib/mysql
